version: '2'
services:
  mysql:
    image: mysql:8.0.12
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  php:
    image: phpmyadmin/phpmyadmin:4.8.3
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
    ports:
      - "8080:80"
